### ISSUE TITLE
Support markdown headings in document symbols

### ISSUE THREAD

**Issue by stefanprobst** [mdx-js/mdx-analyzer#168]
### Subject of the feature

VSCode has a outline panel, which works for markdown files, but currently not for mdx files. It would be great if it would!

### Problem

Currently, the ouline pane shows a "No symbols found in document" message.

### Expected behavior

Document outline should be accessible in outline pane.

### Alternatives

Manually switch the language from "Markdown React" to "Markdown" to get the outline.

**Comment by stefanprobst** [comment]
for markdown this is handled by this [`DocumentSymbolProvider`](https://github.com/microsoft/vscode/blob/main/extensions/markdown-language-features/src/features/documentSymbolProvider.ts), but no idea how to reuse this for mdx

**Comment by JounQin** [comment]
`mdx` requires runtime info, so I think it can not be fully supported, but for previewing simple mdx as markdown, it may be good to have. But I personally don't have much experience on VSCode extension, PR welcome.

**Comment by Temez1** [comment]
For me the code outline works in mdx. Not sure if something has changed?

**Comment by nightire** [comment]
@Temez1 Check the file type info in the status bar. If you see _Markdown_ instead of _Markdown React_, then it must be something/where else to change the file type mapping.

**Comment by remcohaszing** [comment]
The initial IntelliSense added support for document symbols (used by for example the outline pane and breadcrumbs). Currently only JavaScript symbols are supported. I’ll use this issue to track support for markdown headings.

**Comment by remcohaszing** [comment]
Released in `vscode-mdx@1.5.0`, `@mdx-js/language-server@0.2.0` :tada:
