### ISSUE TITLE
Inline code with angle brackets nested in JSX tag causes highlighting to fail

### ISSUE THREAD

**Issue by willcrichton** [mdx-js/mdx-analyzer#183]
### Subject of the issue

If I have a program like this:

```
<Hey>
`<F<` x  
y
</Hey>
```

This has weird syntax highlighting:

![Screen Shot 2021-10-24 at 12 42 08 PM](https://user-images.githubusercontent.com/663326/138610268-3fdebdb4-d734-450a-8b13-bc57f133e0ba.png)

This case is minimal. If I remove e.g. the `F` or an angle bracket `<`, then the highlighting returns to normal:

![Screen Shot 2021-10-24 at 12 42 13 PM](https://user-images.githubusercontent.com/663326/138610272-8bae49e8-8f4c-413e-8515-96b28fa0dcbb.png)

### Your environment

*   **OS**: MacOS
*   **Packages**: n/a
*   **Env**: VSCode 1.61.2, VSCode MDX 0.2.3

**Comment by karlhorky** [comment]
Another example of this:

<img width="564" alt="Screen Shot 2022-01-05 at 18 38 22" src="https://user-images.githubusercontent.com/1935696/148263318-55882a7b-a9ad-4925-9fc0-97c2b688efc7.png">

Code:

````
<RevealAnswer>

abc `a <firstName>`

</RevealAnswer>

error`Unexpected token, expected "{"`

What's the problem here?

```javascript showLineNumbers
function addAndDivideByFive(numberA, numberB)
  console.log('numberA', numberA) {
  const sum = numberA + numberB;
  const result = sum / 5;
  return result;
}
```

Solution: We broke the function statement because we misplaced the `console.log`. The error message already gave us a hint about that. A `{` is expected right after specifying the parameters because the function 
````
