### ISSUE TITLE
Syntax Highlighting is broken for Fragments & components that start with valid Unicode characters

### ISSUE THREAD

**Issue by Enteleform** [mdx-js/mdx-analyzer#191]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

0.23

### Steps to reproduce

**Example 1**
```jsx
<>

  <Ḟoo class="Bar">
    Some Content
  </Ḟoo>

  <Foo class="Bar">
    Some Content
  </Foo>
  
</>
```

**Example 2**
```jsx
<Ḟoo class="Bar">
  Some Content
</Ḟoo>

<Foo class="Bar">
  Some Content
</Foo>
```

### Expected behavior

Syntax highlighting should match the built-in `javascriptreact` syntax when using:
- Fragments `<></>`
- Components that start with [Valid Characters](https://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names/9337047#9337047) such as `Ḟ`

### Actual behavior

Syntax highlighting is broken.

![image](https://user-images.githubusercontent.com/10906415/148929525-9b82b38e-f937-41ef-9535-fb26f6106bda.png)

### Runtime

Node v16

### Package manager

yarn v1

### OS

Windows

### Build and bundle tools

Vite

**Comment by vicary** [comment]
Adding to the context, a simple double line-break will break the syntax highlighting.

It doesn't matter if it's a Fragment or a simple `<p>`, breaks in both cases.

| Works                                                                                                                                                                | Doesn't Work                                                                                                                                                         |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="367" alt="Screenshot 2023-01-01 at 15 28 48" src="https://user-images.githubusercontent.com/85772/210163804-835bfc09-9002-4cf5-a8a6-45022469fe5b.png" /> | <img width="366" alt="Screenshot 2023-01-01 at 15 28 57" src="https://user-images.githubusercontent.com/85772/210163811-1bf2345a-e175-4605-8815-604a7ecca3b7.png" /> |
