### ISSUE TITLE
Syntax highlighting stops working when indented

### ISSUE THREAD

**Issue by cibulka** [mdx-js/mdx-analyzer#209]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

VSCode MDX v0.3.2

### Steps to reproduce

Use the attached MDX file in archive in VSCode 1.69.2 with VSCode MDX v0.3.2.

[vscode-mdx-indent-test.mdx.zip](https://github.com/mdx-js/vscode-mdx/files/9226951/vscode-mdx-indent-test.mdx.zip)

### Expected behavior

Syntax highlighting should preferably happen at all times, meaning:
1. if inside wrapper (either indented or not)
2. if indented

If the markdown usage of tabs conflicts with this, then at least the wrappers should work.

### Actual behavior

First of all, thanks for a cool extension!

It stops working for me however when it is indented and/or wrapped in another element.

Here's the MDX in question (I've attached the file above):

```
## Heading highlighted

<Wrapper>
    ## Heading not highlighted 
    - List item 1 
    - List item 2
</Wrapper>

    ## This is also not highlighted

<Wrapper>
## Neither is this
</Wrapper>

```

<img width="1022" alt="Screenshot 2022-07-30 at 18 45 18" src="https://user-images.githubusercontent.com/3989833/181933492-2b9ce9a9-a93e-435d-991f-dc6c91cfccf9.png">

I use a lot of wrappers in my MDX files, so this sort of breaks the extension for me...

### OS

macOS

**Comment by kolodziejczak-sz** [comment]
I'm also struggling with this error, MDX `v1.0.2`:
![vscode-mdx-bug](https://user-images.githubusercontent.com/16175875/185741787-0f5cf256-5f1e-433d-aebf-1c3298ffb972.gif)

**Comment by darrenbarklie** [comment]
Similar issue for me in authoring MDX for Astro.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/3026261/189326840-88030c02-076f-4bd8-8540-2c4276bfbc4a.png">

Oddly, if I indent the HTML, the MD highlighting returns, though I'm _not_ suggesting this as a workaround. :)

<img width="427" alt="image" src="https://user-images.githubusercontent.com/3026261/189327143-82f0cdd7-cc16-4acb-bf40-fb28c7ffcd14.png">

**Comment by cibulka** [comment]
Is there any progress with this? I think it's a pretty crucial thing to fix. :(

**Comment by vecerek** [comment]
Same here:

No-indent "workaround":

<img width="423" alt="Screenshot 2022-11-06 at 02 15 08" src="https://user-images.githubusercontent.com/5737996/200126885-dabb58eb-3909-447e-a983-7981d72862a0.png">

With indent "workaround":

<img width="423" alt="Screenshot 2022-11-06 at 02 15 49" src="https://user-images.githubusercontent.com/5737996/200126919-ab952c2c-eb74-4e6b-9bcc-bde9e83f7829.png">

**Comment by eXifreXi** [comment]
I can also confirm the exact behavior as outlined above. Would love to know if there is a solution to this or if peeps are even properly aware of it. (:

It doesn't even need opening and closing tags to be indented. As soon as the opening tag is not indented it starts failing to highlight the inner markdown. Doesn't seem to break everything though, as HTML is still working fine.

![image](https://user-images.githubusercontent.com/8512512/204142003-7aa1839c-7c3d-411f-9d8b-3d57eeb6fb55.png)
![image](https://user-images.githubusercontent.com/8512512/204142010-9a33b3fa-82c8-4960-a2fb-8cb5c0ba9e2b.png)
