### ISSUE TITLE
Incorrect comments for ES syntaxes

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx-analyzer#221]
I can confirm that the latest version `v1.0.3` uses the correct syntax now when using the comment shortcut for embedded markdown:
```jsx
{/* ## Headings */}
```

__but__ it doesn't work on ESM import/exports or embedded JavaScript:
```jsx
// export const foo = "bar";
```

_Originally posted by @michaeloliverx in https://github.com/mdx-js/vscode-mdx/issues/203#issuecomment-1226907677_

**Comment by JounQin** [comment]
`export const foo = "bar";` is recognized as `ES module syntax`, so its comments are `//` by default. It needs some kind of investigation.

cc @remcohaszing

Do you have any experience about this?

**Comment by remcohaszing** [comment]
Unfortunately not. I added syntax highlighting for Monaco editor in https://github.com/microsoft/monaco-editor/pull/3096. It doesn’t have this specific issues, but it does have some other issues and overall textmate is a more powerful format for syntax highlighting.
