### ISSUE TITLE
Host the demo

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx-analyzer#261]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

This project has a demo for the Monaco editor integration similar to https://monaco-tailwindcss.js.org, https://monaco-unified.js.org, and https://monaco-yaml.js.org. It would be nice if this demo is hosted somewhere as well.

### Solution

The projects mentioned are hosted using Netlify, which is also nice for review environments.

### Alternatives

We could also host on Vercel, like https://mdxjs.com. Maybe we want the styling to match https://mdxjs.com and host it on https://monaco.mdxjs.com.

**Comment by wooorm** [comment]
Not yet, they’re working on it though. Might never happen but it’s a bit promising.
Anyway, do we really need that? Presumably the tests check much more than a demo

**Comment by remcohaszing** [comment]
The GitHub action is ready.

On https://github.com/mdx-js/vscode-mdx/settings/pages, `Source` needs to be set to `GitHub Actions` and a custom domain needs to be configured. I don’t have access though.

Personally I’m in favor of using https://monaco.mdxjs.com.

**Comment by ChristianMurphy** [comment]
> On https://github.com/mdx-js/vscode-mdx/settings/pages, Source needs to be set to GitHub Actions

Done

> custom domain needs to be configured. I don’t have access though.

This part I don't have access to either

**Comment by remcohaszing** [comment]
Thanks! The build is now succesful, so that’s good to know.

https://mdx-js.github.io/vscode-mdx/

**Comment by tippfelher** [comment]
![image](https://github.com/mdx-js/mdx-analyzer/assets/49718037/a41618ca-3bac-4129-a3ce-77f333dc61af)

**Comment by remcohaszing** [comment]
The Monaco integration was removed in favor of Volar. Use [`@volar/monaco`](https://github.com/volarjs/volar.js/tree/master/packages/monaco) if you would like to use this with Monaco editor.

**Comment by CapitaineToinon** [comment]
Hey, sorry to revive an old thread but are there examples around on using mdx with monaco via volar, if that's how we're supposed to do it? I've been fiddling around but I'm pretty lost to be honest. I'm trying to setup use monaco to edit MDX stored in my database and I believe this package is where I should be looking at.

**Comment by remcohaszing** [comment]
You can have a look at [`@volar/monaco`](https://github.com/volarjs/volar.js/tree/master/packages/monaco.)

You should be able to add the language plugin from [`@mdx-js/language-service`](https://github.com/mdx-js/mdx-analyzer/tree/main/packages/language-service) for MDX language support and the service plugin for extra functionality, such as syntax error reporting.

**Comment by websiddu** [comment]
A demo with @volar/monaco and @mdx-js/language-service integration would be greatly apricated and it will be super useful to show case all the featured of mdx-analyzer
