### ISSUE TITLE
Unable to enclose selected word into backticks

### ISSUE THREAD

**Issue by jviteker** [mdx-js/mdx-analyzer#312]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

&gt;= 1.2.3

### Steps to reproduce

Select a word, press backtick. 

### Expected behavior

Selected word is enclosed in backticks.

### Actual behavior

Selected word is replaced with backtick.

This is caused by https://github.com/mdx-js/vscode-mdx/pull/302. 

But to me this behavior seems buggy. 

To me backtick in markdown is a formatting sequence and should behave as other formatting sequences, e.g. double star.

Can this at least be customized in extension setting?

**Comment by remcohaszing** [comment]
I think it makes sense to keep it away from `autoClosingPairs`, but re-include it in `surroundingBrackets`. This way, when pressing a <kbd>\`</kbd>, it doesn’t close automatically, but when selecting a range of text, and then pressing <kbd>\`</kbd>, it will surround the selection.

Does that seem like reasonable behaviour?

cc @TomasHubelbauer

---

This behaviour is hardcoded in [`language-configuration.json`](https://github.com/mdx-js/mdx-analyzer/blob/main/packages/vscode-mdx/language-configuration.json). I don’t think it can be made configrable (easily).

**Comment by TomasHubelbauer** [comment]
I think what you describe makes sense. I wasn't sure the difference between `autoClosingPairs` and `surroundingBrackets` so I disabled both for the backtick in my PR "to be sure". But I think disabling just `autoClosingPairs` will be the most desirable behavior.

**Comment by remcohaszing** [comment]
Same for me, but I just gave it a try to make sure, and it works as I described. :)
