### ISSUE TITLE
Yesterday's release broke some mdx syntax highlighting for me

### ISSUE THREAD

**Issue by kentcdodds** [mdx-js/mdx-analyzer#318]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vscode-mdx

### Steps to reproduce

Install the latest version of vscode-mdx
Open a markdown file with some markdown, even simple markdown will do. Here are some examples:

```md
# Hello world

This **should** be highlighted
```

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1500684/227630902-2d73c0b4-207a-40ed-9280-7d1305723b55.png">

```md
import Comp from './comp'

<Comp prop={34} prop2="hi">
  This: `should be syntax highlighted`.
</Comp>
```

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1500684/227631237-c1ca5510-fb41-4753-9eef-d7196f1694dd.png">

```md
## This should be highlighted

And _this_ should be too...
```

![image](https://user-images.githubusercontent.com/1500684/227631785-8b0f2c70-a168-44e6-bc15-defcc3803930.png)

```md
This is a list:

- why
- are
- these
- hyphens
- green?

No big deal, just kinda surprised...
```

![image](https://user-images.githubusercontent.com/1500684/227632025-322a20b4-3561-4af5-8e9f-8dd1bdfb14bb.png)

### Expected behavior

Things like headings, strong, italics, and inline code blocks should be highlighted.

### Actual behavior

The colors are either non-existent or different from what I was used to before. The components look great though 👍

I'm using Night Owl, but these behaviors show up in others as well. I guess what I would really like is if my MDX highlighting looked as close to the regular markdown highlighting as possible.

Here's what the examples above look like with regular markdown highlighting in Night Owl:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1500684/227633381-b05ee777-4abb-4295-acf8-2715942e3d1e.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1500684/227633441-32110b1c-35a4-44e2-9905-512f30c0cb1f.png">

(Yeah, MDX does better on this one for sure)

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1500684/227633618-1dbc816f-7da9-435f-bca7-06c9320dbd53.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1500684/227633721-377d0247-6b97-4700-b810-2a9a313d17d0.png">

This could just be a case of "someone moved my cheese," but I do think there could be something wrong with the highlighting of the headings, strong, italics, and text in the back-tics.

Thanks!

### Runtime

Node v18

### Package manager

npm v9

### OS

macOS

**Comment by wooorm** [comment]
Hi Kent! Thanks for taking the time to test it out and provide feedback!

I’m going to move this to https://github.com/wooorm/markdown-tm-language. That’s where the code is. This grammar will also be used in other places, with other users, so it’s useful to have the discussions there.
There’s also a demo there: https://wooorm.com/markdown-tm-language/. Which is useful to compare. Because everyone’s themes are different.

**Comment by remcohaszing** [comment]
I’m closing this issue in favor of the upstream one.
