### ISSUE TITLE
Drag and Drop to create Markdown images and videos in MDX files

### ISSUE THREAD

**Issue by karlhorky** [mdx-js/mdx-analyzer#322]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Quickly authoring MDX documents by dragging and dropping images and videos is a nice DX

There is [a drag and drop feature introduced in VS Code 1.70](https://github.com/microsoft/vscode/issues/5240#issuecomment-1204493403) (thanks @mjbvz) that allowed for handling dropped files (either from the VS Code explorer, editor tabs, the OS, or other applications) ([extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/drop-on-document)) - activate this feature by holding shift while dragging a file.

With Markdown files (`*.md`), VS Code allows for creating a Markdown image or video:

https://user-images.githubusercontent.com/1935696/236184496-d8087b79-8297-4580-b2ae-581d81701c54.mp4

https://user-images.githubusercontent.com/1935696/236186216-6eaa43c5-0433-4311-9191-40b244ce0c46.mp4

It would be amazing if creating Markdown images and videos with drag and drop was also supported in an MDX file. Currently, as of VS Code 1.78, it just inserts the path:

https://user-images.githubusercontent.com/1935696/236184544-e85bdc8b-c361-4de2-a23f-add1d6d7e3c2.mp4

### Solution

Apparently in VS Code 1.78 (April 2023) - or maybe earlier - there is an option for extensions to contribute their own options to this list:

> VS Code includes a few built-in ways to drop common content formats. Extensions can also add their own drop options using the `DocumentDropEditProvider` API.

Source: https://code.visualstudio.com/updates/v1_78#_drop-selector

Maybe this would be the way to contribute this action of "Insert Markdown Image"

### Alternatives

Installing the [Drag And Drop Import Relative Path extension](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.drag-import-relative-path) by @ElecTreeFrying

**Comment by wooorm** [comment]
How far should this be taken? What should we generate?

- What about other markdown, or MDX, files? Are there more formats? CSS? JS/JSX/TS/TSX?
- Should we generate markdown images? Or an `<img>`, `<Image>`? I think markdown.
- `<video>`, `<Video>`? What attributes?
- For videos, what about other source formats? User might drop an `.mp4`, and have an `.webm` next to it, should we figure that out and inject that too? Or, should someone drop multiple video files to get it turned? Or, can a user first drop one file, which turns into a video, and then drop another somewhere inside it, in which case a `<source>` is added?
- What URLs should be used? Presumably, MDX is compiled and runs from somewhere else (some bundle), so we’d need to be aware of where assets will be hosted, perhaps they aren’t, or somewhere else entirely?

**Comment by karlhorky** [comment]
I would suggest just copying the relatively simple VS Code implementation for a start - only handle single files, and insert (using relative paths):

- Markdown for images
- HTML element for videos

And only all drag + drop to `*.mdx` files.

I think that's probably the 80% or even 90% use case.

**Comment by karlhorky** [comment]
Wonder if this [Copy external media files into workspace on drop or paste for Markdown](https://code.visualstudio.com/updates/v1_79#_copy-external-media-files-into-workspace-on-drop-or-paste-for-markdown) from VS Code 1.79 (May 2023) is going to also just work out of the box, when this feature is implemented 😍


https://github.com/mdx-js/mdx-analyzer/assets/1935696/8427506d-0675-4d7e-aa42-f12512d93789

**Comment by karlhorky** [comment]
Thanks for the PR at #345 @remcohaszing 🙌 

One question regarding this note from #345:

> When dropping an image, the image is downloaded next to the file, and a markdown link is generated

When dragging and dropping an existing image from the VS Code tree (eg. an image which is either a sibling or in a different directory), I am guessing that it doesn't download the image again, right?

**Comment by remcohaszing** [comment]
It doesn’t handle images dragged from the file tree apparently, only from the web. But it definitely makes sense to do so. I’ll fix that right away.

**Comment by karlhorky** [comment]
Thanks @remcohaszing , awesome 🚀 

I judge from the `semver/minor` label and the current version of `1.4.0` on [the Releases page](https://github.com/mdx-js/mdx-analyzer/releases) and [the extension page](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) that this will be released in a future `1.5.0` version?

**Comment by remcohaszing** [comment]
Yes. I really want to implement #349 in this release. That’s currently the only blocker (but not a hard one). Expect a release very soon.

I love the enthousiasm and would love your feedback and any promotion on social media :heart:

**Comment by remcohaszing** [comment]
Released in `vscode-mdx@1.5.0`, `@mdx-js/language-server@0.2.0`, `@mdx-js/language-service@0.2.0` :tada: 

Re promotion: feel free to retweet https://twitter.com/remcohaszing/status/1722621607620059512 :smile:

**Comment by karlhorky** [comment]
Finally got some time to look at this.

Just trying to make a video of this feature for X/Twitter and I'm having trouble activating the feature. Am I doing something wrong?

I would expect that dragging a `.png` file into an `.mdx` file while holding Shift would cause an image tag to be created in that MDX (either Markdown image syntax or `<img>` tag)


https://github.com/mdx-js/mdx-analyzer/assets/1935696/0f4890c4-2d94-4fdd-a948-8c2904c497ce

**Comment by remcohaszing** [comment]
I’ve confirmed and found the problem.

You can drop images from external sources, but not reference local files. I’m working on it right now.

**Comment by karlhorky** [comment]
@remcohaszing I was making a video to test this just now, and it almost works! The path seems to be 1 level incorrect though (the `../` should be `./` or just ``, an empty string)

https://github.com/mdx-js/mdx-analyzer/assets/1935696/12bc7f08-de41-49ac-89eb-359ec98169ad

Paths:

- `slide-decks/partials/ciCd/index.mdx`
- `slide-decks/partials/ciCd/ci-cd-pipeline.png`

**Comment by remcohaszing** [comment]
Fixed in 31f1912328a688d2e5c943f3f8923c7fee75cc98.

**Comment by karlhorky** [comment]
Great, just tested this in 1.6.1 of the VS Code and it works, thanks! 🚀 did some posts about it:

- https://twitter.com/karlhorky/status/1737656079092498773
- https://bsky.app/profile/karlhorky.bsky.social/post/3kgzkt5b3bc2c
- https://www.threads.net/@karlhorky/post/C1GWSICLesZ

**Comment by karlhorky** [comment]
I edited this issue to be image-only and moved the video parts to a new issue:

- https://github.com/mdx-js/mdx-analyzer/issues/378
