### ISSUE TITLE
[vscode-mdx] Default syntax highlighting

### ISSUE THREAD

**Issue by silverqx** [mdx-js/mdx-analyzer#324]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Is it possible to set a default syntax highlighting for code blocks?

I have something like this in my `Docusaurus` config:
```
    prism: {
      theme: lightCodeTheme,
      darkTheme: darkCodeTheme,
      defaultLanguage: 'cpp',
      additionalLanguages: ['cmake', 'powershell'],
    },
```

So when I have some code block in my MDX document intended by 4 spaces then I would expect automatic highlighting as the cpp code block.

But these code blocks are not correctly `cpp` highlighted in the `vscode` editor. 😞

Currently, if I want to have also syntax highlighting in the `vscode` editor I have to be explicit and I have to provide the ` ```cpp` tag.

### Solution

Would be really helpful to be able to provide a default syntax highlighting to the `vscode-mdx` extension.

### Alternatives

None

**Comment by remcohaszing** [comment]
Syntax highlighting is handled by a static configuration. It can’t be customized.

Also MDX analyzer uses MDX 2, which no longer supports indented code blocks. (See https://mdxjs.com/docs/what-is-mdx/#markdown)

**Comment by silverqx** [comment]
> I recommend being explicit about your code

I'm also an advocate of being explicit but until it disturbs the clarity. I'm going to leave it 4 spaces indented until it works, if it stops working I can easily refactor it although I don't like it very much.

Currently, the docs are very well readable in the raw form, if I add the ` ```cpp` tags everywhere the raw docs start looking more messy.
