### ISSUE TITLE
Quote scope not working

### ISSUE THREAD

**Issue by jmatsushita** [mdx-js/mdx-analyzer#326]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.3.0

### Steps to reproduce

I was trying to setup a different style in vscode using the following snippet in my `settings.json` (note that this work for the `markup.quote.markdown` with the markdown language extension:
```json
  "editor.tokenColorCustomizations": {
    "[Default Dark Modern]": {
      "textMateRules": [
        {
          "scope": "markup.quote.markdown",
          "settings": {
            "foreground": "#ebf6c2"
          }
        },
        {
          "scope": "markup.quote.mdx",
          "settings": {
            "foreground": "#ebf6c2"
          }
        }
      ]
    }
  },
```

However, it didn't work, and the using the command palette's `Developer: Inspect Editor Tokens and Scopes` option, I can see (cf. attached screen recording) that the scope only surrounds the opening token and the following space `> `, but not the actual blockquote content itself.

 

https://github.com/mdx-js/mdx-analyzer/assets/356097/739f196f-697d-4892-be3e-c6370607d607

### Expected behavior

- `tokenColorCustomizations` should work
- `Developer: Inspect Editor Tokens and Scopes` should show the scope of the blockquote continuing into its content.

### Actual behavior

- `tokenColorCustomizations` doesn't work
- `Developer: Inspect Editor Tokens and Scopes` shows the scope of the blockquote only contains the `> ` prefix.

**Comment by wooorm** [comment]
Hey! grammars are maintained somewhere else :)

**Comment by jmatsushita** [comment]
Sounds good! Thanks for the quick fix 🙏  Can we hope for a new release soon?

**Comment by remcohaszing** [comment]
I think it’s time for a new release soon, also to include some other changes. I can make a new release next week.

**Comment by wooorm** [comment]
@remcohaszing Ping! :)
