### ISSUE TITLE
Rename in javascript does not work when mdx.experimentalLanguageServer is enabled

### ISSUE THREAD

**Issue by ambarvm** [mdx-js/mdx-analyzer#327]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unifiedjs.vscode-mdx v1.3.0

### Steps to reproduce

1. Enable `mdx.experimentalLanguageServer`
```json
"mdx.experimentalLanguageServer": true
```
2. Open a project in vscode containing both javascript and mdx files
3. Open a javascript file and right click a variable. Click "Rename Symbol".

### Expected behavior

An input box should appear to allow the variable rename operation.

### Actual behavior

A tooltip appears saying "The element can't be renamed." 

<img width="727" alt="image" src="https://github.com/mdx-js/mdx-analyzer/assets/44284655/23d9b051-3d79-4795-a258-d3f082085c8e">

### Runtime

Node v18

### Package manager

npm v9

### OS

macOS

### Build and bundle tools

webpack

**Comment by remcohaszing** [comment]
I just enabled [version 1.5.0](https://github.com/mdx-js/mdx-analyzer/releases/tag/vscode-mdx%401.5.0) of the VS Code extension. The implementation got a complete rewrite. This issue should be resolved. Please report a new issue if this problem still persists.
