### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tippfelher** [mdx-js/mdx-analyzer#333]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

I copy&pasted the steps under https://github.com/mdx-js/mdx-analyzer/tree/HEAD/demo

i.e.

```
git clone https://github.com/mdx-js/mdx-analyzer.git
cd mdx-analyzer
npm install
npm start
```

but opening in browser yields:

![image](https://github.com/mdx-js/mdx-analyzer/assets/49718037/d303139b-afbc-412e-9f9f-7a9648b7e63d)

### Expected behavior

No "compile" errors as in the screenshot above.

### Actual behavior

See steps to reproduce.

### Runtime

Node v18

### Package manager

npm v9

### OS

Windows

### Build and bundle tools

webpack

**Comment by remcohaszing** [comment]
I can’t reproduce this. I think it’s related to Windows file paths. Does it work if you replace the regex on line 26 in `demo/webpack.config.js` with `/[\\/]fixtures[\\/]demo[\\/]/`?

**Comment by fnatte** [comment]
> I can’t reproduce this. I think it’s related to Windows file paths. Does it work if you replace the regex on line 26 in `demo/webpack.config.js` with `/[\\/]fixtures[\\/]demo[\\/]/`?

Yes, that regex solves this issue for me (using Windows 10).
