### ISSUE TITLE
MDX VS Code extension auto-formatting is indenting tags and removing text (may be IntelliSense issue)

### ISSUE THREAD

**Issue by rdlauer** [mdx-js/mdx-analyzer#355]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.5

### Steps to reproduce

**With the "Enable experimental IntelliSense support for MDX files." checked/enabled**, the MDX extension is turning code like this:

```
<If cond={props.something === 'whatever'}>

### blah blah

</If>
```

into this...

```
      <If cond={props.something === 'whatever'}>



      </If>
```

So it's indenting the if statement for some reason AND more importantly it's removing the content within the tags.

### Expected behavior

It shouldn't be indenting and seriously shouldn't be removing code :)

### Actual behavior

See above.

### OS

macOS

**Comment by ChristianMurphy** [comment]
Hey @rdlauer! 👋 
Sorry you ran into a spot of trouble.
For triage purposes.

1.  What were the steps you followed to see this?
    Did you run a formatting step? Did you run a script?
2.  What version of VSCode are you using?
    ```bash
    code --version
    ```
3.  What other extensions do you have installed in your VSCode?
    ```bash
    code --list-extensions
    ```

**Comment by rdlauer** [comment]
1. I didn't run a formatting step (at least I don't think so...honestly with VS Code these days I'm not entirely sure). The reason I think it's this extension's issue is the fact that I toggled off that IntelliSense setting and the behavior reverted to what I was expecting!
2. 1.84.2
3. aeschli.vscode-css-formatter
batisteo.vscode-django
dbaeumer.vscode-eslint
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
Ionic.ionic
joedevivo.vscode-circuitpython
jtjoo.classic-asp-html
KevinRose.vsc-python-indent
magicstack.MagicPython
ms-python.black-formatter
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.cpptools
ms-vscode.remote-explorer
ms-vscode.vscode-serial-monitor
NativeScript.nativescript
njpwerner.autodocstring
pflannery.vscode-versionlens
platformio.platformio-ide
streetsidesoftware.code-spell-checker
unifiedjs.vscode-mdx
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
Vue.volar
wholroyd.jinja

**Comment by ChristianMurphy** [comment]
I'm not able to replicate the issue locally with version 1.5.0 🤔 

![Screenshot 2023-11-16 132003](https://github.com/mdx-js/mdx-analyzer/assets/3107513/47f5a101-d699-427e-aa15-50d96bd5fa53)
![Screenshot 2023-11-16 132033](https://github.com/mdx-js/mdx-analyzer/assets/3107513/d18e2f2f-6a74-4d61-8999-0b7bf3a13552)

---

@rdlauer could you try disabling all extensions, then enabling only the MDX plugin?

![Screenshot 2023-11-16 132649](https://github.com/mdx-js/mdx-analyzer/assets/3107513/9ac5d19e-3d6d-4fbc-9301-6ff2542bb4c2)

**Comment by rdlauer** [comment]
Good idea - I disabled all extensions except for MDX (and re-enabled that experimental IntelliSense setting). Same problem!

Unchecked the IntelliSense setting and it doesn't alter the formatting (same behavior as before).

**Comment by ChristianMurphy** [comment]
Another thing to check.
If you call save without format from the command palette:
![Screenshot 2023-11-16 134031](https://github.com/mdx-js/mdx-analyzer/assets/3107513/7f0e8fd0-cb84-49ba-88a1-b99589138adc)
does the file get modified?

**Comment by rdlauer** [comment]
It does NOT get formatted in this case!

**Comment by ChristianMurphy** [comment]
Okay, you have format on save enabled for all files.
I can replicate this issue now, thanks @rdlauer!

@remcohaszing is there any other information which would be helpful for debugging?

**Comment by remcohaszing** [comment]
Thanks for reporting / triaging!

I could not have predicted this behaviour, but it makes sense with some deeper knowledge. I will disable formatting in an upcoming version.

For now, a workaround is to disable formatting for MDX

```jsonc
// VS Code settings.json
{
  "[mdx]": {
    "editor.formatOnSave": false
  }
}
```

**Comment by wooorm** [comment]
So Volar is linting and formatting MDX as markdown? Meaning broken linting and formatting? That sounds like a serious bug?

**Comment by remcohaszing** [comment]
Volar maps the JSX and the markdown parts of MDX to virtual files, applies operations on those virtual files, and maps the results back to the original files. This works really well for showing squiggly lines, code navigation, and small edits (such as completions), but not always for formatting.

A bit more in depth: We provide Volar with a virtual file that looks somewhat like this:

```jsx
export function MDXContent() {
  return (
    <>
<If cond={props.something === 'whatever'}>

·············

</If>
    </>
  )
}
```

This gets passed to TypeScript for formatting. TypeScript transforms it into this:

```jsx
export function MDXContent() {
  return (
    <>
      <If cond={props.something === 'whatever'}>



      </If>
    </>
  )
}
```

The changes are then mapped back to the MDX document.

This idea works perfect for certain constructs of embedded content, such as Vue single component files or Astro files, or even just props in MDX content or frontmatter, but this particular transform doesn’t really work for JSX elements in MDX, which is an integral part.

So the solution is to explicitly disable support for formatting MDX files, or at least for the JSX parts.
