### ISSUE TITLE
User defined `export default` in `.mdx` should be allowed

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx-analyzer#362]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vscode-mdx

### Steps to reproduce

```mdx
export   default     ({children   }) => < div> Content {    children}</div>
```

Run on https://mdxjs.com/playground/

### Expected behavior

<img width="2447" alt="image" src="https://github.com/mdx-js/mdx-analyzer/assets/8336744/009bf477-2bc7-4a80-95ee-8208d2d1e394">

### Actual behavior

<img width="850" alt="image" src="https://github.com/mdx-js/mdx-analyzer/assets/8336744/b36cd7bb-c483-472e-9ff9-4e34a3022c6a">

### Runtime

Node v20

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Rollup

**Comment by remcohaszing** [comment]
Ah yes, I can see why this happens. I’m reworking virtual files internally to make them more flexible. This will open up the possibility to fix this.
