### ISSUE TITLE
auto-complete is not triggered by typing

### ISSUE THREAD

**Issue by Zamiell** [mdx-js/mdx-analyzer#385]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

## Description

Auto-complete in MDX files works by pressing `Ctrl` + `Enter`, but not by typing, which makes it dissimilar to how auto-complete works in normal markdown files.

This should be fixed such that typing in .md fiiles and .mdx files works identically.

See: https://github.com/orgs/mdx-js/discussions/2424

**Comment by remcohaszing** [comment]
This was fixed by 433b87cf75024ee1db19734e4eaedc012e0a573c
