### ISSUE TITLE
IntelliSense support for tsconfig paths

### ISSUE THREAD

**Issue by joshuaavalon** [mdx-js/mdx-analyzer#397]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently, intelliSense only support relative path but not `compilerOptions.paths` in `tsconfig.json`.

![image](https://github.com/mdx-js/mdx-analyzer/assets/7152420/fb360bfb-3007-4942-8cf4-4c7d164d5f02)
![image](https://github.com/mdx-js/mdx-analyzer/assets/7152420/9511c468-fe63-4d61-8287-1d8ffaf089a2)

TypeScript intelliSense supports `compilerOptions.paths` and it would be nice if MDX supports it too.

**tsconfig.json**
```json
{
  "compilerOptions": {
    "paths": { "@/*": ["src/*"] }
  }
}
```

### Solution

Resolve intelliSense with paths alias like TypeScript.

### Alternatives

The currently solution is to use relative path, even though both of them can be compiled.

**Comment by remcohaszing** [comment]
I tried to reproduce it, but it works as expected. Make sure you’re using the latest version of the MDX VSCode extension.

If the problem persists, provide a repository which demonstrates this problem.

**Comment by joshuaavalon** [comment]
I have created a example repository. https://github.com/joshuaavalon/mdx-bug

Please see `src/index.mdx`

![image](https://github.com/mdx-js/mdx-analyzer/assets/7152420/02653a53-6d48-4123-8f20-2ac0c977c54f)
![image](https://github.com/mdx-js/mdx-analyzer/assets/7152420/474bc8ca-20cc-42a4-9885-0f2253352be6)


System info
```
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```
MDX extension version is `v1.7.1`

**Comment by remcohaszing** [comment]
That reproduction is helpful. :)

The `tsconfig.json` file defines a TypeScript project. By default project includes all known files in the same folder as the project configuration file. You define the `"include"` option. This excludes all files that don’t adhere to the include pattern. For files that don’t adhere to this pattern, VSCode falls back to the default language service, meaning none of the options specified in `tsconfig.json` are applied to MDX files. One effect that you noticed, is that `paths` isn’t picked up.

The simplest fix for your problem, is to add `"src/**/*.mdx"` to the `"include"` array.

In a future version you may also need to enable `"allowJs"`.

One more tip: You shouldn’t use the deprecated compiler option `"moduleResolution": "node"` anymore. Use `"moduleResolution": "bundler"` or `"module": "nodenext"` instead. For Next.js, you should use `"bundler"`.
