### ISSUE TITLE
JS Fenced code block breaks highlighting when indented

### ISSUE THREAD

**Issue by XiNiHa** [mdx-js/mdx-analyzer#421]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vscode-mdx@1.8.2

### Steps to reproduce

Open an MDX file in VSCode, write this:
~~~mdx
<Comp>
```js
console.log(0);
```
</Comp>

<Comp>
  ```ts
  console.log(0);
  ```
</Comp>

<Comp>
  ```js
  console.log(0);
  ```
</Comp>
~~~

### Expected behavior

All should be highlighted correctly.

### Actual behavior

The first two works correctly. But the last one breaks and continues to pretend like JS even after the fence.

**Comment by remcohaszing** [comment]
I don’t understand what you mean. This is what I’m seeing:

![The provided code snippet in Visual Studio Code](https://github.com/mdx-js/mdx-analyzer/assets/779047/61eeee57-242c-4e8a-8ed3-7614b97c8471)

Is this somehow incorrect? Are you seeing something else? Can you provide a screenshot?

**Comment by XiNiHa** [comment]
That's weird, I'm seeing this
![image](https://github.com/mdx-js/mdx-analyzer/assets/8155259/d1bfdcb9-b16c-4c0f-8c5c-24fa51ca9b94)

**Comment by XiNiHa** [comment]
Oh well, it was a wrong interaction with [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) extension. Removing the extension fixed it.

**Comment by remcohaszing** [comment]
Does it also cause this issue for JavaScript in HTML / Astro / Vue?

**Comment by XiNiHa** [comment]
![image](https://github.com/mdx-js/mdx-analyzer/assets/8155259/f1adb837-4bcd-443e-9438-68b5bcf21c25)
![image](https://github.com/mdx-js/mdx-analyzer/assets/8155259/6358c0e1-c6c7-4021-b9d6-123b645f1304)

Looks like the issue also applies to them, maybe it's a Volar issue then?

**Comment by remcohaszing** [comment]
Volar doesn’t handle syntax highlighting. That’s handled by TextMate grammars. It’s not something I’m super familiar with, but it looks like the [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) extension doesn’t properly close a particular scope. It’s a bug in that extension, not here.
