### ISSUE TITLE
Keyboard shortcuts conflict with VS Code shortcuts

### ISSUE THREAD

**Issue by rdebeasi** [mdx-js/mdx-analyzer#422]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX for Visual Studio Code v1.8.2

### Steps to reproduce

1. Open Visual Studio Code.
2. Confirm that MDX for Visual Studio Code is installed.
3. Open a Markdown file.
4. Press Cmd+B (or ctrl+B).

More info on this keyboard shortcut:
- MDX shortcut: #353
- VS Code shortcut https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout

### Expected behavior

Sidebar toggles.

### Actual behavior

Sidebar does not toggle.

To confirm that the MDX plugin's keyboard shortcut is taking precedence:

1. Press Cmd+P (or Control+P) and choose "Preferences: Open Keyboard Shortcuts"
2. In the "type to search" field, type "Cmd+B" (or "ctrl+B"). 
3. Note that MDX "toggle strong" keyboard shortcut has taken precedence over VS Code's "Toggle Primary Side Bar Visibility" keyboard shortcut.

Would it be possible to choose a default shortcut that does not overlap with existing VS Code shortcuts? Thank you!

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
Welcome @rdebeasi! 👋 
A counter point. Markdown is a document language.
Pretty much every document editor uses `ctrl + b` for bold/strong text.

* Word (https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-word-95ef89dd-7142-4b50-afb2-f762f663ceb2)
* Google docs (https://support.google.com/docs/answer/179738?hl=en&co=GENIE.Platform%3DDesktop)
* Gutenberg/Wordpress (https://www.zettahost.com/wordpress-tutorials/gutenberg-keyboard-shortcuts/)
* And many more

As a default, `ctrl + B` for bold feels reasonable, it's what every other editor does, choosing something different would be unexpected to most users.
Though you are welcome to re-bind on your personal editor it if you feel that fast access to the sidebar is more of a priority to your document editing experience.

**Comment by remcohaszing** [comment]
The rationale is indeed as @ChristianMurphy describes. Also [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) has the same behaviour.

I do understand your point, but I don’t think it’s generally better to use a different default shortcut. If you want to use <kbd>Ctrl</kbd> + <kbd>B</kbd> for toggling the side bar, you can use a custom key mapping.

I do notice just now that the toggle commands are broken, which I will look into.

**Comment by rdebeasi** [comment]
Makes sense - thanks for explaining the thinking there! I'll go ahead and close this issue.

**Comment by guesant** [comment]
there is a way to disable this shortcuts in the extension settings?

**Comment by ChristianMurphy** [comment]
You can customize, overide, or disable using settings.
See the vscode keybinding docs:

https://code.visualstudio.com/docs/configure/keybindings

**Comment by hamza512b** [comment]
For myself, I do not see why the MDX plugin even tries to override VSCode behavior. This is a code editor, not a blog post editor. I know that you can override it, but it seems to me like unreasonable defaults.
