### ISSUE TITLE
For some reason `vscode-markdown-languageservice` is enabled

### ISSUE THREAD

**Issue by wooorm** [mdx-js/mdx-analyzer#424]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

current

### Steps to reproduce

* clone MDX
* use `vscode-mdx`
* open an MDX file (such as `extending-mdx.mdx`)
* observe that `vscode-markdown-languageservice` (presumably) is emitting diagnostics about broken links

<img width="1239" alt="Screenshot 2024-04-02 at 1 02 44 PM" src="https://github.com/mdx-js/mdx-analyzer/assets/944406/e858a5c3-a6e8-4a06-9572-9acaf3aaec61">

### Expected behavior

MDX is not markdown, so a regular tool that only works on markdown, should not run.
We could have remark run on MDX files, but I‘d want to discuss that in a separate issue.

### Actual behavior

markdown tools that are unaware of MDX run

**Comment by remcohaszing** [comment]
`vscode-markdown-languageservice` works on the generated virtual markdown code. It provides not just diagnostics, but also link references, completions, document outline, etc.

But yes, I did notice some diagnostics that shouldn’t be there.
