### ISSUE TITLE
TypeScript completions appear anywhere in a document without JavaScript mappings

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx-analyzer#427]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

vscode-mdx@1.8.3

### Steps to reproduce

- Open an empty MDX file.
- Type an `a`

### Expected behavior

Nothing happens

### Actual behavior

TypeScript completions pop up.

### Runtime

Node v18

### OS

Linux

**Comment by minazukie** [comment]
Same here. I have rolled back to version 1.7.3 and it works well.
