### ISSUE TITLE
Language Server not picking up manually typed links to other files

### ISSUE THREAD

**Issue by andresantosjor** [mdx-js/mdx-analyzer#436]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.8.5 / VsCode 1.81.1

### Steps to reproduce

1. Create a .MDX file;
2. Type the link syntax. Inside the parenthesis, type the relative or full path to another .MDX file;
3. Autocomplete will activate and suggest the path to you;
4. The same happens to image syntax.

### Expected behavior

After typing the path, the language server should interpret this path as an internal link to the file. Hovering over the link with the mouse, in the editor, should underline it and clicking on it should take you to the file. This happens when you link to a web page, but not when the link is internal.

### Actual behavior

The created link is treated as text.

### Runtime

Node v20

### Package manager

npm v10

### OS

Windows

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
There are many link syntaxes. Please show an input MDX file. Please show what you are writing in it.

**Comment by andresantosjor** [comment]
I'm using the syntax defined by John Gruber for links:

`[text](other_file.mdx) `

In mdx:

![image](https://github.com/mdx-js/mdx-analyzer/assets/44325713/915e05cb-af09-4e44-97c4-6dac76ab5a3b)

In md:

![image](https://github.com/mdx-js/mdx-analyzer/assets/44325713/8bdb2e2f-dff1-444c-8ed4-c25d31fd6806)
