### ISSUE TITLE
Errors in `.mdx` files with `mdx.checkMdx` appear at end of file

### ISSUE THREAD

**Issue by karlhorky** [mdx-js/mdx-analyzer#451]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX VS Code Extension v1.8.9

### Steps to reproduce

1. Set up [the `app-dir-mdx` example from Remco](https://codesandbox.io/p/sandbox/github/remcohaszing/next.js/tree/fix-mdx-components-examples/examples/app-dir-mdx) using the content below

(content contains intentional TypeScript errors)

`mdx-components.tsx`

```tsx
import { MDXComponents } from 'mdx/types';
import { HTMLAttributes } from 'react';

type ZoomImageProps = {
  alt: string;
};

function ZoomImage(props: ZoomImageProps) {
  return <div>www</div>;
}

function CustomCodeSandBox(props: HTMLAttributes<HTMLDivElement>) {
  return (
    <div {...props} />
  );
}

const components = {
  ZoomImage,
  CustomCodeSandBox,
} satisfies MDXComponents;

declare global {
  type MDXProvidedComponents = typeof components;
}

export function useMDXComponents(): MDXProvidedComponents {
  return components;
}
```

`app/message.mdx`

```mdx
<ZoomImage src="/logo.svg" alt="Logo" />

<CustomCodeSandBox template="react" />
```

2. Observe the errors from the MDX VS Code extension appearing on a 1-character red squiggly the end of the file in VS Code instead of on the respective lines where the errors occur:
   ![Screenshot 2024-06-27 at 19 48 42](https://github.com/mdx-js/mdx-analyzer/assets/1935696/fb311356-62f0-4fef-95cb-b5ad3abcf8f9)

### Expected behavior

In the screenshot above, I would expect that the 1st error would appear on line 47, covering the whole line, and the 2nd error would appear on line 49, covering the whole line

### Actual behavior

In the screenshot above, the errors from the MDX VS Code extension appear on a 1-character red squiggly the end of the file in VS Code instead of on the respective lines where the errors occur

### OS

macOS

### Build and bundle tools

Next.js

**Comment by karlhorky** [comment]
Interesting, it appears that this problem goes away if I disable these 2 extensions 🤔

- [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components) by @jasonwilliams (`styled-components.vscode-styled-components`)
- [React CSS modules](https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css) by @Viijay-Kr (`viijay-kr.react-ts-css`)

![Screenshot 2024-06-27 at 23 06 27](https://github.com/mdx-js/mdx-analyzer/assets/1935696/a9b00eaf-b853-4549-ae80-6c44c9b8960b)

**Comment by karlhorky** [comment]
Funny enough, if I disable these 2 extensions, then that also disables the IntelliSense to auto-import into the file:

With the extensions:

![Screenshot 2024-06-27 at 23 07 38](https://github.com/mdx-js/mdx-analyzer/assets/1935696/37b41d2f-c093-4cba-96eb-4ca68d660bed)

With the extensions disabled:

![Screenshot 2024-06-27 at 23 07 30](https://github.com/mdx-js/mdx-analyzer/assets/1935696/3c27f834-70a2-485d-9c31-452be407cd3a)

...or maybe IntelliSense to auto-import is not a feature of MDX Analyzer? 🤔

**Comment by remcohaszing** [comment]
I’m closing this in favour of upstream issue https://github.com/styled-components/vscode-styled-components/issues/448.

I’m not seeing any problems while using `viijay-kr.react-ts-css`.

**Comment by karlhorky** [comment]
Ok, thanks for reporting!

> I’m not seeing any problems while using `viijay-kr.react-ts-css`.

I think this may be only caused by certain settings in [React CSS modules](https://github.com/Viijay-Kr/react-ts-css) by @Viijay-Kr ([`viijay-kr.react-ts-css`](https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css))

eg. here are my settings:

```json
  "reactTsScss.autoComplete": true,
  "reactTsScss.baseDir": "src",
  "reactTsScss.cleanUpDefs": [
    "node_modules/vite/client.d.ts",
    "node_modules/next/types/global.d.ts",
    "node_modules/react-scripts/lib/react-app.d.ts"
  ],
  "reactTsScss.codelens": true,
  "reactTsScss.cssAutoComplete": true,
  "reactTsScss.cssDefinitions": true,
  "reactTsScss.cssSyntaxColor": true,
  "reactTsScss.definition": true,
  "reactTsScss.diagnostics": true,
  "reactTsScss.peekProperties": true,
  "reactTsScss.references": true,
```

**Comment by remcohaszing** [comment]
I’m just not seeing it.

![image](https://github.com/mdx-js/mdx-analyzer/assets/779047/a116c405-f3ba-4b2f-9b5d-85c3e03af3e7)

Possibly another extension is the culprit. All TypeScript plugins interact with each other and can accidentally break other plugins. I even recall one plugin recovered issues from another at some point. Perhaps another extension is the culprit.

The following command lists all VSCode extensions that register a TypeScript plugin.

```sh
grep -l '"typescriptServerPlugins"' ~/.vscode/extensions/*/package.json
```

**Comment by karlhorky** [comment]
Hm, I can repro with only `unifiedjs.vscode-mdx@1.8.9` and `viijay-kr.react-ts-css@3.2.0`

I'll create a reproduction.

**Comment by remcohaszing** [comment]
FWIW this is how I’m testing this:

- ```sh
  git clone git@github.com:mdx-js/mdx-analyzer.git
  cd mdx-analyzer
  npm install
  code .
  ```
- Tweak `fixtures/fixtures.code-workspace` as desired.
- In VSCode, press <kbd>F5</kbd>

**Comment by karlhorky** [comment]
Here's the reproduction (also shows the missing auto-import IntelliSense - I will open a different bug issue for that):

Extensions: `unifiedjs.vscode-mdx@1.8.9` and `viijay-kr.react-ts-css@3.2.0`

```
Version: 1.91.0-insider
Commit: aea213b7fcc7de5c24ad797ac1af209b159d451f
Date: 2024-06-28T06:02:58.030Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

Repo: https://github.com/karlhorky/repro-mdx-analyzer-missing-auto-import-intellisense


https://github.com/mdx-js/mdx-analyzer/assets/1935696/1be8f03f-d318-4dc2-8b15-682310f1f11c

**Comment by karlhorky** [comment]
> Interesting, it appears that the highlighting is in the correct location if I disable these 2 extensions 🤔
> 
> * [vscode-styled-components](https://github.com/styled-components/vscode-styled-components) by @jasonwilliams ([`styled-components.vscode-styled-components`](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components))
> * [React CSS modules](https://github.com/Viijay-Kr/react-ts-css) by @Viijay-Kr ([`viijay-kr.react-ts-css`](https://marketplace.visualstudio.com/items?itemName=viijay-kr.react-ts-css))

Companion issues have been reported in these two VS Code extensions now:

- https://github.com/styled-components/vscode-styled-components/issues/448
- https://github.com/Viijay-Kr/react-ts-css/issues/160

**Comment by remcohaszing** [comment]
I’m re-opening this. A change was made upstream in https://github.com/volarjs/volar.js/pull/216, which fixes compatibility with a number of existing TypeScript plugins. Let’s track here until that change has made its way into MDX analyzer.

**Comment by jasonwilliams** [comment]
Thanks for raising the detailed issue, sadly I've had to archive https://github.com/styled-components/vscode-styled-components due to having no contributors for quite some time. It's unlikely the issue will be fixed there any time soon, I don't know if there's a replacement extension but until then it will remain the way it is.

**Comment by karlhorky** [comment]
> I’m re-opening this. A change was made upstream in [volarjs/volar.js#216](https://github.com/volarjs/volar.js/pull/216), which fixes compatibility with a number of existing TypeScript plugins. Let’s track here until that change has made its way into MDX analyzer.

@remcohaszing Nice, thanks! Considering that https://github.com/volarjs/volar.js/pull/216 was released in [`v2.4.0-alpha.1`](https://github.com/volarjs/volar.js/releases/tag/v2.4.0-alpha.1), I guess the version that will probably have the change will be `v2.4.0`:

- [`v2.4.0`](https://github.com/volarjs/volar.js/releases/tag/v2.4.0)

**Comment by karlhorky** [comment]
@remcohaszing Thanks for the update to Volar 2.4 in #460 and the publish of [`unifiedjs.vscode-mdx@1.8.10`](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) 🙌 

The problem is half fixed: I tried out the new version with [the reproduction repo](https://github.com/karlhorky/repro-mdx-analyzer-missing-auto-import-intellisense) from [the original issue description](https://github.com/mdx-js/mdx-analyzer/issues/451#issue-2378768575) and:

1. Correct error locations are used with the (deprecated) Styled Components VS Code extension
2. Incorrect error locations (end of file) still appear with the React CSS modules VS Code extension (related issue: https://github.com/Viijay-Kr/react-ts-css/issues/160)

https://github.com/user-attachments/assets/ab2edde5-1827-40f7-9f74-606eb4a8cc48

**Comment by Viijay-Kr** [comment]
@karlhorky Re posting here for visibility 

This PR https://github.com/Viijay-Kr/typescript-cleanup-defs/pull/5 adapts the similar changes compared to volar . Hopefully this fixes the issue fully

**Comment by karlhorky** [comment]
@Viijay-Kr thanks for the publish of `viijay-kr.react-ts-css@3.2.4`, I can confirm the MDX errors are in the correct positions again! 🎉


https://github.com/user-attachments/assets/2e204850-b517-4873-962a-a65dafcf2ff4
