### ISSUE TITLE
Saving to External Drive in Fedora 40 with KDE Plasma

### ISSUE THREAD

**Issue by faruthem** [mdx-js/mdx-analyzer#459]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

0.144.4

### Steps to reproduce

1. Connect an external drive to the computer running Fedora 40.

2. Open an application in which you can save a file or program, such as a text editor or an IDE.

3. Create a new file or program in the application.

4. Make changes to the file or program.

5. Save the file or program to the external drive.

6. Verify that the file or program has been saved correctly to the external drive.

7. Open a terminal and use the ls command to list the files on the external drive.

8. Search for the file or program that was saved earlier.

9. If the file or program appears in the list, it means it was saved correctly.

### Expected behavior

The expected behavior is that files or programs saved to an external drive from Fedora 40 with KDE Plasma should be successfully saved and accessible on the external drive. There should be no discrepancies between the user interface indication of a successful save and the actual state of the files or programs on the external drive.

### Actual behavior

When attempting to save files or programs to an external drive in Fedora 40 with KDE Plasma, the user interface indicates that the save operation was successful. However, the files or programs are not actually saved to the external drive as expected.

### OS

Linux

**Comment by faruthem** [comment]
This discrepancy between the expected and actual behavior suggests a potential issue with file system interactions, KDE Plasma's file management, or a conflict with external drive drivers.

**Comment by remcohaszing** [comment]
This issue seems unrelated to MDX. Did you report this to the wrong project?
