### ISSUE TITLE
Syntax highlighting breaks when anything is after `{}`

### ISSUE THREAD

**Issue by KianNH** [mdx-js/mdx-analyzer#480]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unifiedjs.vscode-mdx v1.8.10

### Steps to reproduce

Paste the following snippets into separate MDX files:

````mdx
{props.name}

```js
export const foo = "bar";
```

[foo](/bar/)
````

````mdx
{props.name} a

```js
export const foo = "bar";
```

[foo](/bar/)
````

It looks like this can also be reproduced with GitHub's highlighting, so maybe it's an issue with the grammar?

### Expected behavior

Both should have the same syntax highlighting.

### Actual behavior

The second one, with a character after the brackets, has broken syntax highlighting.

### Runtime

Node v21

**Comment by wooorm** [comment]
Thanks! I think I have it.

**Comment by sebas1208** [comment]
I found a probably related issue with code blocks inside JSX components. 

![image](https://github.com/user-attachments/assets/dbb1d4fb-7473-48ae-aaa4-1b871326f3e0)

the closing tag is still recognized as ruby code.
