### ISSUE TITLE
Headings H3 - H6 are assigned incorrect textmate scopes

### ISSUE THREAD

**Issue by icorbrey** [mdx-js/mdx-analyzer#483]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.8.11

### Steps to reproduce

1. Paste the following text into a VSCode window:
```md
# Heading 1

## Heading 2

### Heading 3

#### Heading 4

##### Heading 5

###### Heading 6
```
2. Execute "Developer: Inspect Editor Tokens and Scopes" through the `Ctrl`+`Shift`+`P` menu
3. Inspect the scopes of each heading

### Expected behavior

Since H1 is assigned `markup.heading.atx.1` and H2 is assigned `markup.heading.atx.2`, H3 - H6 should be assigned `markup.heading.atx.3`, `markup.heading.atx.4`, and so on.

### Actual behavior

H3 - H6 are all assigned `markup.heading.atx.2`.

### Affected runtime and version

Not sure, it's in the most recent version of VSCode

### Affected OS and version

Ubuntu 22.04.5 LTS

**Comment by icorbrey** [comment]
A visual example of what's occurring, I'm writing a theme that differentiates each heading level with color and this is currently broken on MDX. Expected: 
![image](https://github.com/user-attachments/assets/8c14bc11-9e0c-4a52-95db-1b852cdf7046)

Actual: 
![image](https://github.com/user-attachments/assets/3c68950a-d0ff-470f-b055-fcbd9ea2c603)

**Comment by icorbrey** [comment]
Looks like the issue is upstream in https://github.com/wooorm/markdown-tm-language, should be an easy fix? H3 - H6 are already targeted in the TMLanguage file, just not assigned the right IDs

**Comment by icorbrey** [comment]
PR is in to hopefully fix this at https://github.com/wooorm/markdown-tm-language/pull/12

**Comment by wooorm** [comment]
Hi!

Have you tested that your changes work with GitHub and some common/default VS Code themes?

Often, themes don’t support all scopes.

**Comment by wooorm** [comment]
I think for GH this will be fine. That’s just looking at `markup.heading`.

**Comment by remcohaszing** [comment]
It might be interesting to know of this breaks any things. But even if this breaks a theme, this change makes sense IMO. Themes can adapt.

**Comment by icorbrey** [comment]
Is there a reason H3 - H6 were assigned H2 scopes?

**Comment by icorbrey** [comment]
Okay so after looking a fair amount I can't really see anything that is explicitly relying on H3 - H6 all having H2 scope, but some that already rely on headings having the correct scope that get broken in MDX. For example, [Catppuccin Frappe from Catppuccin for VSCode](https://github.com/catppuccin/vscode/blob/bbb0b5a231a082790398613266e56268ae2e4de0/packages/catppuccin-vsc/src/theme/tokens/markdown.ts#L7-L92)

![image](https://github.com/user-attachments/assets/b9f38bb3-ff6f-406b-ba2c-6bf543297095)

Searching for [files not using deeper headings](https://github.com/search?q=markup.heading.atx.2+AND+NOT+markup.heading.atx.3&type=code) shows that pretty much repo that references H2 scopes and not any deeper ones is just bundling https://github.com/wooorm/markdown-tm-language instead of doing something meaningful with it.

Now I can't speak on GitHub, as I don't know where I'd even begin to look for their implementations let alone if they're source available, but from my surface level lookover I can't see anywhere that they'd be relying on this behavior. They seem to not care what level a heading is wherever I look.

**Comment by wooorm** [comment]
For GH, see my earlier comment https://github.com/mdx-js/mdx-analyzer/issues/483#issuecomment-2467876802. As for source, see e.g. https://github.com/primer/github-syntax-dark/blob/master/lib/github-dark.css.

Thanks for checking!

**Comment by icorbrey** [comment]
Ah, I think I missed that comment. Thanks!
