### ISSUE TITLE
Function as Child Component

### ISSUE THREAD

**Issue by kocobee** [mdx-js/mdx-analyzer#485]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=issues) and [discussions](https://github.com/orgs/mdx-js/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

@mdx-js/typescript-plugin@0.0.6

### Steps to reproduce

Create a function as child component w/ some nesting, i.e. 

```
<Foo arr={bleh}>
  {name => 
    <>
      <Bar>
        <Baz>{name}</Baz>
      </Bar>
    </>
  }
</Foo>
```

### Actual behavior

Get a syntax error:

<img width="235" alt="Screenshot 2024-12-12 at 2 20 18 PM" src="https://github.com/user-attachments/assets/99a00a74-e473-4b39-aad5-b8dfae8b13b2" />

<img width="518" alt="Screenshot 2024-12-12 at 2 23 56 PM" src="https://github.com/user-attachments/assets/f9a940c6-c54d-44cd-8a64-67bda0e2e6bd" />

### Expected behavior

No syntax error

**Comment by remcohaszing** [comment]
Thanks for reporting and including a reproduction!

Cross reference: https://github.com/orgs/mdx-js/discussions/2514
